INSERT INTO teams (`country`, `isocode`, `group_char`) VALUES
  ('Russian Federation', 'RU', 'A'),
  ('Saudi Arabia', 'SA', 'A'),
  ('Egypt', 'EG', 'A'),
  ('Uruguay', 'UY', 'A'),
  ('Morocco', 'MA', 'B'),
  ('Iran', 'IR', 'B'),
  ('Portugal', 'PT', 'B'),
  ('Spain', 'ES', 'B'),
  ('Australia', 'AU', 'C'),
  ('Peru', 'PE', 'C'),
  ('France', 'FR', 'C'),
  ('Denmark', 'DK', 'C'),
  ('Argentina', 'AR', 'D'),
  ('Nigeria', 'NG', 'D'),
  ('Iceland', 'IS', 'D'),
  ('Croatia', 'HR', 'D'),
  ('Serbia', 'RS', 'E'),
  ('Brazil', 'BR', 'E'),
  ('Costa Rica', 'CR', 'E'),
  ('Switzerland', 'CH', 'E'),
  ('Germany', 'DE', 'F'),
  ('Republic of Korea', 'KR', 'F'),
  ('Mexico', 'MX', 'F'),
  ('Sweden', 'SE', 'F'),
  ('Panama', 'PA', 'G'),
  ('England', 'EN', 'G'),
  ('Belgium', 'BE', 'G'),
  ('Tunisia', 'TN', 'G'),
  ('Poland', 'PL', 'H'),
  ('Japan', 'JP', 'H'),
  ('Senegal', 'SN', 'H'),
  ('Colombia', 'CO', 'H');
