INSERT INTO team (`country`, `isocode`, `group_char`) VALUES
  ('Russian Federation', 'RU', 'A'),
  ('Saudi Arabia', 'SA', 'A'),
  ('Egypt', 'EG', 'A'),
  ('Uruguay', 'UY', 'A'),
  ('Morocco', 'MA', 'B'),
  ('Iran', 'IR', 'B'),
  ('Portugal', 'PT', 'B'),
  ('Spain', 'ES', 'B'),
  ('Australia', 'AU', 'C'),
  ('Peru', 'PE', 'C'),
  ('France', 'FR', 'C'),
  ('Denmark', 'DK', 'C'),
  ('Argentina', 'AR', 'D'),
  ('Nigeria', 'NG', 'D'),
  ('Iceland', 'IS', 'D'),
  ('Croatia', 'HR', 'D'),
  ('Serbia', 'RS', 'E'),
  ('Brazil', 'BR', 'E'),
  ('Costa Rica', 'CR', 'E'),
  ('Switzerland', 'CH', 'E'),
  ('Germany', 'DE', 'F'),
  ('Republic of Korea', 'KR', 'F'),
  ('Mexico', 'MX', 'F'),
  ('Sweden', 'SE', 'F'),
  ('Panama', 'PA', 'G'),
  ('England', 'EN', 'G'),
  ('Belgium', 'BE', 'G'),
  ('Tunisia', 'TN', 'G'),
  ('Poland', 'PL', 'H'),
  ('Japan', 'JP', 'H'),
  ('Senegal', 'SN', 'H'),
  ('Colombia', 'CO', 'H');

INSERT INTO location (`name`, `city`, `country`) VALUES
  ('Olympiastadion Luschniki', 'Moskau', 'Russland'),
  ('Spartak-Stadion', 'Moskau', 'Russland'),
  ('Zentralstadion', 'Jekaterinburg', 'Russland'),
  ('Kaliningrad-Stadion', 'Kaliningrad', 'Russland'),
  ('Kasan-Arena', 'Kasan', 'Russland'),
  ('Stadion Nischni Nowgorod', 'Nischni Nowgorod', 'Russland'),
  ('Rostow Arena', 'Rostow am Don', 'Russland'),
  ('Kosmos-Arena', 'Samara', 'Russland'),
  ('Mordowia Arena', 'Saransk', 'Russland'),
  ('Olympiastadion Sotschi', 'Sotschi', 'Russland'),
  ('Sankt-Petersburg-Stadion', 'Sankt Petersburg', 'Russland'),
  ('Wolgograd Arena', 'Wolgograd', 'Russland');