spring:
  datasource:
    username: betting
    password: game
    url: jdbc:mariadb://localhost/bettinggame
    hikari:
      max-lifetime: 300000
      idle-timeout: 200000
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 20000
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB103Dialect
    open-in-view: false

  messages:
    basename: i18n/AdminMessages,i18n/CommonMessages,i18n/ErrorMessages,i18n/Version

  thymeleaf:
    mode: HTML

logging:
  file: application.log
  level:
    root: info
    de.bettinggame: debug
