spring:
  datasource:
    username: betting
    password: game
    url: jdbc:mariadb://localhost/bettinggame

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  messages:
    basename: i18n/AdminMessages,i18n/CommonMessages,i18n/ErrorMessages

  thymeleaf:
    mode: HTML

logging:
  file: application.log
  level:
    root: info
    de.bettinggame: debug
