spring:
  mvc:
    static-path-pattern: /static/**

  datasource:
    data-username:
    data-password:
    username:
    password:
    schema:
    url: jdbc:mariadb://localhost/bettinggame

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true

  messages:
    basename: i18n/AdminMessages,i18n/CommonMessages

  thymeleaf:
    mode: HTML

logging:
  file: application.log
  level:
    root: info
    de.bettinggame: debug

endpoints:
  flyway:
    sensitive: false
  metrics:
    sensitive: false