INSERT INTO team (`name_de`, `name_en`, `team_key`, `group_char`) VALUES
  ('Russland', 'Russian Federation', 'RU', 'A'),
  ('Saudi Arabien', 'Saudi Arabia', 'SA', 'A'),
  ('Ägypten', 'Egypt', 'EG', 'A'),
  ('Uruguay', 'Uruguay', 'UY', 'A'),
  ('Marokko', 'Morocco', 'MA', 'B'),
  ('Iran', 'Iran', 'IR', 'B'),
  ('Portugal', 'Portugal', 'PT', 'B'),
  ('Spanien', 'Spain', 'ES', 'B'),
  ('Australien', 'Australia', 'AU', 'C'),
  ('Peru', 'Peru', 'PE', 'C'),
  ('Frankreich', 'France', 'FR', 'C'),
  ('Dänemark', 'Denmark', 'DK', 'C'),
  ('Argentinien', 'Argentina', 'AR', 'D'),
  ('Nigeria', 'Nigeria', 'NG', 'D'),
  ('Island', 'Iceland', 'IS', 'D'),
  ('Kroatien', 'Croatia', 'HR', 'D'),
  ('Serbien', 'Serbia', 'RS', 'E'),
  ('Brasilien', 'Brazil', 'BR', 'E'),
  ('Costa Rica', 'Costa Rica', 'CR', 'E'),
  ('Schweiz', 'Switzerland', 'CH', 'E'),
  ('Deutschland', 'Germany', 'DE', 'F'),
  ('Republik Korea', 'Republic of Korea', 'KR', 'F'),
  ('Mexiko', 'Mexico', 'MX', 'F'),
  ('Schweden', 'Sweden', 'SE', 'F'),
  ('Panama', 'Panama', 'PA', 'G'),
  ('England', 'England', 'EN', 'G'),
  ('Belgien', 'Belgium', 'BE', 'G'),
  ('Tunesien', 'Tunisia', 'TN', 'G'),
  ('Polen', 'Poland', 'PL', 'H'),
  ('Japan', 'Japan', 'JP', 'H'),
  ('Senegal', 'Senegal', 'SN', 'H'),
  ('Kolumbien', 'Colombia', 'CO', 'H');

INSERT INTO location (`short_key`, `name_de`, `name_en`, `city_de`, `city_en`, `country_de`, `country_en`) VALUES
  ('RUS_MOS_LUS', 'Olympiastadion Luschniki', 'Luzhniki Stadium', 'Moskau', 'Moscow', 'Russland', 'Russian Federation'),
  ('RUS_MOS_SPA', 'Spartak-Stadion', 'Spartak Stadium', 'Moskau', 'Moscow', 'Russland', 'Russian Federation'),
  ('RUS_JEK_ZEN', 'Zentralstadion', 'Ekaterinburg Arena', 'Jekaterinburg', 'Yekaterinburg', 'Russland', 'Russian Federation'),
  ('RUS_KAL_KAL', 'Kaliningrad-Stadion', 'Kaliningrad-Stadium', 'Kaliningrad', 'Kaliningrad', 'Russland', 'Russian Federation'),
  ('RUS_KAS_KAS', 'Kasan-Arena', 'Kazan Arena', 'Kasan', 'Kazan', 'Russland', 'Russian Federation'),
  ('RUS_NIS_NOW', 'Stadion Nischni Nowgorod', 'Nizhny Novgorod Stadium', 'Nischni Nowgorod', 'Nizhny Novgorod', 'Russland', 'Russian Federation'),
  ('RUS_ROS_ROS', 'Rostow Arena', 'Rostov Arena', 'Rostow am Don', 'Rostov-on-Don', 'Russland', 'Russian Federation'),
  ('RUS_SAM_KOS', 'Kosmos-Arena', 'Cosmos Arena', 'Samara', 'Samara', 'Russland', 'Russian Federation'),
  ('RUS_SAR_MOR', 'Mordowia Arena', 'Mordovia Arena', 'Saransk', 'Saransk', 'Russland', 'Russian Federation'),
  ('RUS_SOT_SOT', 'Olympiastadion Sotschi', 'Fisht Stadium', 'Sotschi', 'Sochi', 'Russland', 'Russian Federation'),
  ('RUS_PET_PET', 'Sankt-Petersburg-Stadion', 'Saint Petersburg Stadium', 'Sankt Petersburg', 'Saint Petersburg', 'Russland', 'Russian Federation'),
  ('RUS_WOL_WOL', 'Wolgograd Arena', 'Volgograd Arena', 'Wolgograd', 'Volgograd', 'Russland', 'Russian Federation');