INSERT INTO team (`name_de`, `name_en`, `team_key`, `group_char`) VALUES
  ('Russland', 'Russian Federation', 'RU', 'A'),
  ('Saudi Arabien', 'Saudi Arabia', 'SA', 'A'),
  ('Ägypten', 'Egypt', 'EG', 'A'),
  ('Uruguay', 'Uruguay', 'UY', 'A'),
  ('Marokko', 'Morocco', 'MA', 'B'),
  ('Iran', 'Iran', 'IR', 'B'),
  ('Portugal', 'Portugal', 'PT', 'B'),
  ('Spanien', 'Spain', 'ES', 'B'),
  ('Australien', 'Australia', 'AU', 'C'),
  ('Peru', 'Peru', 'PE', 'C'),
  ('Frankreich', 'France', 'FR', 'C'),
  ('Dänemark', 'Denmark', 'DK', 'C'),
  ('Argentinien', 'Argentina', 'AR', 'D'),
  ('Nigeria', 'Nigeria', 'NG', 'D'),
  ('Island', 'Iceland', 'IS', 'D'),
  ('Kroatien', 'Croatia', 'HR', 'D'),
  ('Serbien', 'Serbia', 'RS', 'E'),
  ('Brasilien', 'Brazil', 'BR', 'E'),
  ('Costa Rica', 'Costa Rica', 'CR', 'E'),
  ('Schweiz', 'Switzerland', 'CH', 'E'),
  ('Deutschland', 'Germany', 'DE', 'F'),
  ('Republik Korea', 'Republic of Korea', 'KR', 'F'),
  ('Mexiko', 'Mexico', 'MX', 'F'),
  ('Schweden', 'Sweden', 'SE', 'F'),
  ('Panama', 'Panama', 'PA', 'G'),
  ('England', 'England', 'EN', 'G'),
  ('Belgien', 'Belgium', 'BE', 'G'),
  ('Tunesien', 'Tunisia', 'TN', 'G'),
  ('Polen', 'Poland', 'PL', 'H'),
  ('Japan', 'Japan', 'JP', 'H'),
  ('Senegal', 'Senegal', 'SN', 'H'),
  ('Kolumbien', 'Colombia', 'CO', 'H');

INSERT INTO location (`short_key`, `name`, `city`, `country`) VALUES
  ('RUS_MOS_LUS', 'Olympiastadion Luschniki', 'Moskau', 'Russland'),
  ('RUS_MOS_SPA', 'Spartak-Stadion', 'Moskau', 'Russland'),
  ('RUS_JEK_ZEN', 'Zentralstadion', 'Jekaterinburg', 'Russland'),
  ('RUS_KAL_KAL', 'Kaliningrad-Stadion', 'Kaliningrad', 'Russland'),
  ('RUS_KAS_KAS', 'Kasan-Arena', 'Kasan', 'Russland'),
  ('RUS_NIS_NOW', 'Stadion Nischni Nowgorod', 'Nischni Nowgorod', 'Russland'),
  ('RUS_ROS_ROS', 'Rostow Arena', 'Rostow am Don', 'Russland'),
  ('RUS_SAM_KOS', 'Kosmos-Arena', 'Samara', 'Russland'),
  ('RUS_SAR_MOR', 'Mordowia Arena', 'Saransk', 'Russland'),
  ('RUS_SOT_SOT', 'Olympiastadion Sotschi', 'Sotschi', 'Russland'),
  ('RUS_PET_PET', 'Sankt-Petersburg-Stadion', 'Sankt Petersburg', 'Russland'),
  ('RUS_WOL_WOL', 'Wolgograd Arena', 'Wolgograd', 'Russland');